# Generated by Django 5.2.4 on 2025-11-05 00:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_borrowrecord_late_fee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='borrowrecord',
            constraint=models.CheckConstraint(condition=models.Q(due_date__gt=models.F('borrow_date')), name='check_due_date_after_borrow_date'),
        ),
    ]
