# Generated by Django 5.2.4 on 2025-11-06 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_phone_number_user_phone_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimecode',
            name='purpose',
            field=models.CharField(choices=[('activation', 'Activation'), ('login', 'Login'), ('password_reset', 'Password Reset'), ('phone_verification', 'Phone Verification')], max_length=20),
        ),
    ]
